[build]
  base = "client"
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

# Netlify Functions (kept inside client/netlify/functions)
[functions]
  directory = "netlify/functions"

# SPA fallback so client-side routes work on refresh
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
